enum errors {ERROR = -1 ,
                UF_MAT_NAME, 
                UF_CMD_NAME, 
                ARG_N_REAL_NUM, 
                EXTRA_TEXT, 
                MISS_ARG, 
                MISS_COMMA, 
                ILLEGAL_COMMA, 
                MULT_CONSEC_COMMA, 
                ARG_N_SCALAR, 
                ALLOC_FAILD};